# fly.toml file generated for further-from on 2022-12-18T21:04:04-05:00

app = "further-from"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

# [deploy]
#   release_command = "/app/bin/migrate"

[mounts]
 source = "furtherfrom_data"
 destination = "/data"

[env]
  DATABASE_PATH = "/data/furtherfrom_data/furtherfrom_prod.db"
  PHX_HOST = "furtherfrom.com"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    grace_period = "1s"
    interval = "15s"
    method = "get"
    path = "/up.txt"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    [services.http_checks.headers]
      X-Forwarded-Proto = "https"
